package filemigrate_test

import (
	"context"
	"errors"
	"testing"

	"github.com/sofired/grizzle/kit/filemigrate"
)

// --- MemManagedSourceStore ---

func TestMemManagedSourceStore_EmptyDirRejected(t *testing.T) {
	store := filemigrate.NewMemManagedSourceStore()
	_, err := store.ResolveSourceRoot(t.Context(), "")
	if err == nil {
		t.Fatal("expected error for empty dir")
	}
	if !errors.Is(err, filemigrate.ErrInvalidConfig) {
		t.Errorf("expected ErrInvalidConfig, got %v", err)
	}
}

func TestMemManagedSourceStore_ResolveSucceeds(t *testing.T) {
	store := filemigrate.NewMemManagedSourceStore()
	root, err := store.ResolveSourceRoot(t.Context(), "/out")
	if err != nil {
		t.Fatalf("ResolveSourceRoot: %v", err)
	}
	if root.RealPath != "/out" {
		t.Errorf("RealPath = %q, want %q", root.RealPath, "/out")
	}
}

func TestMemManagedSourceStore_WriteAndReadBack(t *testing.T) {
	store := filemigrate.NewMemManagedSourceStore()
	root, err := store.ResolveSourceRoot(t.Context(), "/out")
	if err != nil {
		t.Fatal(err)
	}

	const header = "// Code generated by Grizzle. DO NOT EDIT.\n"
	content := []byte(header + "package schema\n")

	mf, err := store.WriteManagedFile(t.Context(), root, "users.go", content, filemigrate.ManagedWriteOptions{
		Header: header,
	})
	if err != nil {
		t.Fatalf("WriteManagedFile: %v", err)
	}
	if mf.RelPath != "users.go" {
		t.Errorf("RelPath = %q, want %q", mf.RelPath, "users.go")
	}
	if !mf.Written {
		t.Error("Written should be true for a new file")
	}
	var zero filemigrate.Digest
	if mf.ContentSHA256 == zero {
		t.Error("ContentSHA256 must not be zero")
	}
}

func TestMemManagedSourceStore_OverwriteOwnedFileSucceeds(t *testing.T) {
	store := filemigrate.NewMemManagedSourceStore()
	root, _ := store.ResolveSourceRoot(t.Context(), "/out")

	const header = "// Code generated by Grizzle. DO NOT EDIT.\n"
	first := []byte(header + "package schema // v1\n")
	second := []byte(header + "package schema // v2\n")

	if _, err := store.WriteManagedFile(t.Context(), root, "users.go", first, filemigrate.ManagedWriteOptions{Header: header}); err != nil {
		t.Fatalf("first write: %v", err)
	}
	mf, err := store.WriteManagedFile(t.Context(), root, "users.go", second, filemigrate.ManagedWriteOptions{Header: header})
	if err != nil {
		t.Fatalf("second write: %v", err)
	}
	if !mf.Written {
		t.Error("Written should be true when content changed")
	}
}

func TestMemManagedSourceStore_WrittenFalseWhenContentUnchanged(t *testing.T) {
	store := filemigrate.NewMemManagedSourceStore()
	root, _ := store.ResolveSourceRoot(t.Context(), "/out")

	const header = "// Code generated by Grizzle. DO NOT EDIT.\n"
	content := []byte(header + "package schema\n")

	if _, err := store.WriteManagedFile(t.Context(), root, "users.go", content, filemigrate.ManagedWriteOptions{Header: header}); err != nil {
		t.Fatal(err)
	}
	// Second write with identical content.
	mf, err := store.WriteManagedFile(t.Context(), root, "users.go", content, filemigrate.ManagedWriteOptions{Header: header})
	if err != nil {
		t.Fatalf("second write: %v", err)
	}
	if mf.Written {
		t.Error("Written should be false when content is unchanged")
	}
}

// TestMemManagedSourceStore_EmptyHeaderRejected verifies that an empty
// ManagedWriteOptions.Header is rejected with ErrInvalidConfig before any
// overwrite decision runs. The ManagedSourceStore contract permits
// overwriting only files carrying the recognized managed header, so an
// empty header (which would treat every existing file as managed) must not
// be accepted — otherwise tests or custom callers could silently clobber
// hand-written schema files instead of returning ErrManagedFileOverwrite.
func TestMemManagedSourceStore_EmptyHeaderRejected(t *testing.T) {
	store := filemigrate.NewMemManagedSourceStore()
	root, _ := store.ResolveSourceRoot(t.Context(), "/out")

	// Seed a hand-written file that does NOT carry any managed header.
	store.AddFile("/out", "handwritten.go", []byte("package schema // human-written\n"))

	// Empty header must be rejected even with no preexisting file at the path,
	// to enforce the contract uniformly regardless of overwrite state.
	_, err := store.WriteManagedFile(t.Context(), root, "fresh.go",
		[]byte("package schema\n"),
		filemigrate.ManagedWriteOptions{Header: ""})
	if err == nil {
		t.Fatal("expected error for empty header on fresh write")
	}
	if !errors.Is(err, filemigrate.ErrInvalidConfig) {
		t.Errorf("fresh write: expected ErrInvalidConfig, got %v", err)
	}

	// Empty header must also be rejected when a hand-written file exists at
	// the path — the pre-fix code would silently overwrite it.
	_, err = store.WriteManagedFile(t.Context(), root, "handwritten.go",
		[]byte("package schema // overwritten by buggy header\n"),
		filemigrate.ManagedWriteOptions{Header: ""})
	if err == nil {
		t.Fatal("expected error for empty header over hand-written file")
	}
	if !errors.Is(err, filemigrate.ErrInvalidConfig) {
		t.Errorf("overwrite hand-written: expected ErrInvalidConfig, got %v", err)
	}
}

func TestMemManagedSourceStore_UnownedFileRejected(t *testing.T) {
	store := filemigrate.NewMemManagedSourceStore()
	root, _ := store.ResolveSourceRoot(t.Context(), "/out")

	// Seed a file that does NOT carry the managed header.
	store.AddFile("/out", "handwritten.go", []byte("package schema // human-written\n"))

	const header = "// Code generated by Grizzle. DO NOT EDIT.\n"
	_, err := store.WriteManagedFile(t.Context(), root, "handwritten.go", []byte(header+"package schema\n"),
		filemigrate.ManagedWriteOptions{Header: header})
	if err == nil {
		t.Fatal("expected error for unowned file overwrite")
	}
	if !errors.Is(err, filemigrate.ErrManagedFileOverwrite) {
		t.Errorf("expected ErrManagedFileOverwrite, got %v", err)
	}
}

// TestMemManagedSourceStore_NegativeLimitRejected verifies that a negative
// field in ResourceLimits is rejected with ErrInvalidConfig before any size
// comparison runs, so that managed-source-store error semantics match the
// other public stores (MemArtifactStore, FSArtifactStore, MemSourceStore,
// FSSourceStore) instead of silently returning ErrResourceLimit after a
// comparison against a negative value.
func TestMemManagedSourceStore_NegativeLimitRejected(t *testing.T) {
	store := filemigrate.NewMemManagedSourceStore()
	root, err := store.ResolveSourceRoot(t.Context(), "/out")
	if err != nil {
		t.Fatal(err)
	}

	const header = "// Code generated by Grizzle. DO NOT EDIT.\n"
	cases := []struct {
		name   string
		limits filemigrate.ResourceLimits
	}{
		{"MaxRenderedSourceFileBytes", filemigrate.ResourceLimits{MaxRenderedSourceFileBytes: -1}},
		{"MaxRenderedSourceBytes", filemigrate.ResourceLimits{MaxRenderedSourceBytes: -1}},
		{"MaxSchemaFiles", filemigrate.ResourceLimits{MaxSchemaFiles: -1}},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			_, err := store.WriteManagedFile(t.Context(), root, "users.go",
				[]byte(header+"package schema\n"),
				filemigrate.ManagedWriteOptions{Header: header, Limits: tc.limits})
			if !errors.Is(err, filemigrate.ErrInvalidConfig) {
				t.Errorf("expected ErrInvalidConfig, got %v", err)
			}
		})
	}
}

func TestMemManagedSourceStore_ByteCapEnforced(t *testing.T) {
	store := filemigrate.NewMemManagedSourceStore()
	root, _ := store.ResolveSourceRoot(t.Context(), "/out")

	const header = "// Code generated by Grizzle. DO NOT EDIT.\n"
	content := []byte(header + "package schema // lots of content here\n")

	_, err := store.WriteManagedFile(t.Context(), root, "big.go", content, filemigrate.ManagedWriteOptions{
		Header: header,
		Limits: filemigrate.ResourceLimits{MaxRenderedSourceFileBytes: 4},
	})
	if err == nil {
		t.Fatal("expected resource limit error")
	}
	if !errors.Is(err, filemigrate.ErrResourceLimit) {
		t.Errorf("expected ErrResourceLimit, got %v", err)
	}
}

func TestMemManagedSourceStore_CancelledContextRejected(t *testing.T) {
	store := filemigrate.NewMemManagedSourceStore()
	ctx, cancel := context.WithCancel(context.Background())
	cancel() // cancel immediately

	_, err := store.ResolveSourceRoot(ctx, "/out")
	if err == nil {
		t.Fatal("expected error for cancelled context")
	}
}

func TestMemManagedSourceStore_NoFollowContainment(t *testing.T) {
	store := filemigrate.NewMemManagedSourceStore()
	root, _ := store.ResolveSourceRoot(t.Context(), "/out")

	// Write to different roots; the store must not mix them up.
	const header = "// Code generated by Grizzle. DO NOT EDIT.\n"
	content := []byte(header + "package a\n")
	if _, err := store.WriteManagedFile(t.Context(), root, "a.go", content, filemigrate.ManagedWriteOptions{Header: header}); err != nil {
		t.Fatalf("WriteManagedFile: %v", err)
	}

	// A different root must not see the file.
	otherRoot, _ := store.ResolveSourceRoot(t.Context(), "/other")
	mf, err := store.WriteManagedFile(t.Context(), otherRoot, "a.go", content, filemigrate.ManagedWriteOptions{Header: header})
	if err != nil {
		t.Fatalf("WriteManagedFile on other root: %v", err)
	}
	// File did not exist under /other, so Written must be true.
	if !mf.Written {
		t.Error("Written should be true: file was not present under the other root")
	}
}
